name: flutter_vending_machine_kata
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ADDED
  freezed_annotation: ^1.1.0
  adaptive_dialog: ^1.5.0+1

  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:

  freezed: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8

  bloc_test: ^9.0.3
  mocktail: ^0.3.0

flutter:

  uses-material-design: true